### PR TITLE
update (faq) public trackers

### PR DESCRIPTION
**Pull request by Audionut**
Nitpicking the limitation.

When the private flag is _not_ set, the client will happily add multiple trackers to the same infohash.

### CODE REVIEW

**Comment by zakkarry** [comment]
I think the main issue is that we don't have the feature of adding torrent trackers to existing trackers (this has been requested and I think there is still a GHI for this) - so I'm not entirely sure the behavior, particularly across ALL clients, is something worth mentioning?

There is the case for whether this works if you saved and added them yourself I suppose, but as said I'm not sure this has feature parity across all the clients and potentially requires explicit naming of which would support this type of workflow.

by the way, I appreciate your contributions thus far.

**Comment by mmgoodnow** [comment]
FWIW multiple announce urls are supported in all major clients.

**Comment by zakkarry** [comment]
> FWIW multiple announce urls are supported in all major clients.

I didn't mean that, I meant whether simply injecting/adding a torrent with the same infohash automatically merges the candidate to the searchee.

**Comment by Audionut** [comment]
Probably not if there's no call to bypass popups. qBit will ask for permission to to merge announce urls iirc.

Wouldn't seem like it's even worth the effort to bother trying. The FAQ is pretty clear about how pointless public tracker support is.

**Pull request merged**
